
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'AppFooter': typeof import("../../app/components/App/Footer.vue")['default']
  'AppNavbar': typeof import("../../app/components/App/Navbar.vue")['default']
  'SectionContact': typeof import("../../app/components/Section/Contact.vue")['default']
  'SectionFurnitureIndoor': typeof import("../../app/components/Section/FurnitureIndoor.vue")['default']
  'SectionFurnitureOutdoor': typeof import("../../app/components/Section/FurnitureOutdoor.vue")['default']
  'SectionHero': typeof import("../../app/components/Section/Hero.vue")['default']
  'SectionWhy': typeof import("../../app/components/Section/Why.vue")['default']
  'ScriptGoogleMapsDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.d.vue")['default']
  'ScriptGoogleMaps': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.vue")['default']
  'ScriptGoogleMapsAdvancedMarkerElementDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.d.vue")['default']
  'ScriptGoogleMapsAdvancedMarkerElement': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.vue")['default']
  'ScriptGoogleMapsCircleDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.d.vue")['default']
  'ScriptGoogleMapsCircle': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.vue")['default']
  'ScriptGoogleMapsHeatmapLayerDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.d.vue")['default']
  'ScriptGoogleMapsHeatmapLayer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.vue")['default']
  'ScriptGoogleMapsInfoWindowDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.d.vue")['default']
  'ScriptGoogleMapsInfoWindow': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.vue")['default']
  'ScriptGoogleMapsMarkerDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.d.vue")['default']
  'ScriptGoogleMapsMarker': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.vue")['default']
  'ScriptGoogleMapsMarkerClustererDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.d.vue")['default']
  'ScriptGoogleMapsMarkerClusterer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.vue")['default']
  'ScriptGoogleMapsPinElementDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.d.vue")['default']
  'ScriptGoogleMapsPinElement': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.vue")['default']
  'ScriptGoogleMapsPolygonDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.d.vue")['default']
  'ScriptGoogleMapsPolygon': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.vue")['default']
  'ScriptGoogleMapsPolylineDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.d.vue")['default']
  'ScriptGoogleMapsPolyline': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.vue")['default']
  'ScriptGoogleMapsRectangleDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.d.vue")['default']
  'ScriptGoogleMapsRectangle': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.vue")['default']
  'ScriptAriaLoadingIndicatorDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.d.vue")['default']
  'ScriptAriaLoadingIndicator': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.vue")['default']
  'ScriptCarbonAdsDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.d.vue")['default']
  'ScriptCarbonAds': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue")['default']
  'ScriptCrispDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.d.vue")['default']
  'ScriptCrisp': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue")['default']
  'ScriptGoogleAdsenseDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.d.vue")['default']
  'ScriptGoogleAdsense': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue")['default']
  'ScriptIntercomDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.d.vue")['default']
  'ScriptIntercom': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue")['default']
  'ScriptLemonSqueezyDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.d.vue")['default']
  'ScriptLemonSqueezy': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue")['default']
  'ScriptLoadingIndicatorDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.d.vue")['default']
  'ScriptLoadingIndicator': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
  'ScriptPayPalButtonsDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.d.vue")['default']
  'ScriptPayPalButtons': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.vue")['default']
  'ScriptPayPalMarksDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.d.vue")['default']
  'ScriptPayPalMarks': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.vue")['default']
  'ScriptPayPalMessagesDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.d.vue")['default']
  'ScriptPayPalMessages': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.vue")['default']
  'ScriptStripePricingTableDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.d.vue")['default']
  'ScriptStripePricingTable': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
  'ScriptVimeoPlayerDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.d.vue")['default']
  'ScriptVimeoPlayer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
  'ScriptYouTubePlayerDVue': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.d.vue")['default']
  'ScriptYouTubePlayer': typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
  'Icon': typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
  'NuxtIsland': typeof import("../../node_modules/@nuxt/hints/dist/runtime/components/nuxt-island")['default']
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  'SchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
  'SchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
  'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
  'SchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
  'SchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
  'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
  'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
  'SchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
  'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
  'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
  'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
  'SchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
  'SchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
  'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
  'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
  'SchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
  'SchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
  'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
  'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
  'SchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
  'SchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
  'SchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
  'SchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
  'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
  'LazyAppFooter': LazyComponent<typeof import("../../app/components/App/Footer.vue")['default']>
  'LazyAppNavbar': LazyComponent<typeof import("../../app/components/App/Navbar.vue")['default']>
  'LazySectionContact': LazyComponent<typeof import("../../app/components/Section/Contact.vue")['default']>
  'LazySectionFurnitureIndoor': LazyComponent<typeof import("../../app/components/Section/FurnitureIndoor.vue")['default']>
  'LazySectionFurnitureOutdoor': LazyComponent<typeof import("../../app/components/Section/FurnitureOutdoor.vue")['default']>
  'LazySectionHero': LazyComponent<typeof import("../../app/components/Section/Hero.vue")['default']>
  'LazySectionWhy': LazyComponent<typeof import("../../app/components/Section/Why.vue")['default']>
  'LazyScriptGoogleMapsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.d.vue")['default']>
  'LazyScriptGoogleMaps': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.vue")['default']>
  'LazyScriptGoogleMapsAdvancedMarkerElementDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.d.vue")['default']>
  'LazyScriptGoogleMapsAdvancedMarkerElement': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.vue")['default']>
  'LazyScriptGoogleMapsCircleDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.d.vue")['default']>
  'LazyScriptGoogleMapsCircle': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.vue")['default']>
  'LazyScriptGoogleMapsHeatmapLayerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.d.vue")['default']>
  'LazyScriptGoogleMapsHeatmapLayer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.vue")['default']>
  'LazyScriptGoogleMapsInfoWindowDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.d.vue")['default']>
  'LazyScriptGoogleMapsInfoWindow': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.vue")['default']>
  'LazyScriptGoogleMapsMarkerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.d.vue")['default']>
  'LazyScriptGoogleMapsMarker': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.vue")['default']>
  'LazyScriptGoogleMapsMarkerClustererDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.d.vue")['default']>
  'LazyScriptGoogleMapsMarkerClusterer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.vue")['default']>
  'LazyScriptGoogleMapsPinElementDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.d.vue")['default']>
  'LazyScriptGoogleMapsPinElement': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.vue")['default']>
  'LazyScriptGoogleMapsPolygonDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.d.vue")['default']>
  'LazyScriptGoogleMapsPolygon': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.vue")['default']>
  'LazyScriptGoogleMapsPolylineDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.d.vue")['default']>
  'LazyScriptGoogleMapsPolyline': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.vue")['default']>
  'LazyScriptGoogleMapsRectangleDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.d.vue")['default']>
  'LazyScriptGoogleMapsRectangle': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.vue")['default']>
  'LazyScriptAriaLoadingIndicatorDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.d.vue")['default']>
  'LazyScriptAriaLoadingIndicator': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.vue")['default']>
  'LazyScriptCarbonAdsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.d.vue")['default']>
  'LazyScriptCarbonAds': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue")['default']>
  'LazyScriptCrispDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.d.vue")['default']>
  'LazyScriptCrisp': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue")['default']>
  'LazyScriptGoogleAdsenseDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.d.vue")['default']>
  'LazyScriptGoogleAdsense': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue")['default']>
  'LazyScriptIntercomDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.d.vue")['default']>
  'LazyScriptIntercom': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue")['default']>
  'LazyScriptLemonSqueezyDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.d.vue")['default']>
  'LazyScriptLemonSqueezy': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue")['default']>
  'LazyScriptLoadingIndicatorDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.d.vue")['default']>
  'LazyScriptLoadingIndicator': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']>
  'LazyScriptPayPalButtonsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.d.vue")['default']>
  'LazyScriptPayPalButtons': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.vue")['default']>
  'LazyScriptPayPalMarksDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.d.vue")['default']>
  'LazyScriptPayPalMarks': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.vue")['default']>
  'LazyScriptPayPalMessagesDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.d.vue")['default']>
  'LazyScriptPayPalMessages': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.vue")['default']>
  'LazyScriptStripePricingTableDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.d.vue")['default']>
  'LazyScriptStripePricingTable': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']>
  'LazyScriptVimeoPlayerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.d.vue")['default']>
  'LazyScriptVimeoPlayer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']>
  'LazyScriptYouTubePlayerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.d.vue")['default']>
  'LazyScriptYouTubePlayer': LazyComponent<typeof import("../../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
  'LazyIcon': LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/@nuxt/hints/dist/runtime/components/nuxt-island")['default']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazySchemaOrgDebug': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']>
  'LazySchemaOrgArticle': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']>
  'LazySchemaOrgBreadcrumb': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']>
  'LazySchemaOrgComment': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgComment']>
  'LazySchemaOrgEvent': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']>
  'LazySchemaOrgFoodEstablishment': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']>
  'LazySchemaOrgHowTo': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']>
  'LazySchemaOrgImage': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgImage']>
  'LazySchemaOrgJobPosting': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']>
  'LazySchemaOrgLocalBusiness': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']>
  'LazySchemaOrgOrganization': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']>
  'LazySchemaOrgPerson': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']>
  'LazySchemaOrgProduct': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']>
  'LazySchemaOrgQuestion': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']>
  'LazySchemaOrgRecipe': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']>
  'LazySchemaOrgReview': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgReview']>
  'LazySchemaOrgVideo': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']>
  'LazySchemaOrgWebPage': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']>
  'LazySchemaOrgWebSite': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']>
  'LazySchemaOrgMovie': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']>
  'LazySchemaOrgCourse': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']>
  'LazySchemaOrgItemList': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']>
  'LazySchemaOrgBook': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgBook']>
  'LazySchemaOrgSoftwareApp': LazyComponent<typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
