// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/27/2025, 12:11:17 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/exiglosi/Documents/Creetech/bro-living/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/exiglosi/Documents/Creetech/bro-living/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/exiglosi/Documents/Creetech/bro-living/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/exiglosi/Documents/Creetech/bro-living/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/exiglosi/Documents/Creetech/bro-living/app/plugins/**/*.{js,ts,mjs}","/Users/exiglosi/Documents/Creetech/bro-living/app/composables/**/*.{js,ts,mjs}","/Users/exiglosi/Documents/Creetech/bro-living/app/utils/**/*.{js,ts,mjs}","/Users/exiglosi/Documents/Creetech/bro-living/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/exiglosi/Documents/Creetech/bro-living/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/exiglosi/Documents/Creetech/bro-living/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/exiglosi/Documents/Creetech/bro-living/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;